{% set python_min = '3.10' %}
{% set name = "pybashify" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pybashify-{{ version }}.tar.gz
  sha256: 1592ef5b158e192db0c3bad16c845b881ca234862269cda15f8710a96cf6a8dd

build:
  entry_points:
    - bashify = pybashify.cli.main:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - typer >=0.12.5,<0.13
    - pydantic >=2.0
    - numpy >=2.1.0,<3
    - astor >=0.8.1,<0.9

test:
  imports:
    - pybashify
  commands:
    - pip check
    - bashify --help
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Use Python to write bash scripts while interop w/ bash
  home: https://pypi.org/project/pybashify/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AmeerArsala
